name: br
description: SuperHero API

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  # shared_preferences: ^0.5.3+4
  bloc_pattern: ^2.4.0+2
  rxdart: ^0.21.0
  cached_network_image: ^2.0.0-rc
  flutter_villains: ^1.2.1
  path_provider: ^1.2.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/bg.png
    - images/logo.png
